### ISSUE TITLE
[1.2]Console app for running tcp server from shell

### ISSUE THREAD

**Issue by EvilLord666** [MossbauerLab/TinyTcpServer#2]
We shoul be able to start, stop or restart server from console, send and receive strings and files, e.t.c

**Comment by EvilLord666** [comment]
This part should be written as extension

**Comment by EvilLord666** [comment]
I think for fully useful console app we should place C# scripting therefore we obtain smart app behavior.

**Comment by EvilLord666** [comment]
This feature will be done after script engine implementation.

**Comment by KatanaZZZ** [comment]
We should pass handle script via cmd line as parameter with ip-address and tcp port and maybe file with server settings.

**Comment by EvilLord666** [comment]
Console app done.
